using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using System.Net;

namespace RentACarData
{
    public class City
    {
        public int Id { get; set; }
        public int ProvinceId { get; set; }
        public string Name { get; set; }

        public virtual Province? Province { get; set; }

        public virtual ICollection<Address> Addresses { get; set; } = new HashSet<Address>();
    }

    public class CityEntityTypeConfiguration : IEntityTypeConfiguration<City>
    {
        public void Configure(EntityTypeBuilder<City> builder)
        {
            builder
                .Property(p => p.Name)
                .HasMaxLength(50);

            builder
                .HasIndex(p => new { p.Name, p.ProvinceId })
                .IsUnique();

            builder
                .HasMany(p => p.Addresses)
                .WithOne(p => p.City)
                .HasForeignKey(p => p.CityId)
                .OnDelete(DeleteBehavior.Cascade);

            builder
                .HasData(
                new City { Id = 1, Name = "Seyhan", ProvinceId = 1 },
                new City { Id = 2, Name = "Ceyhan", ProvinceId = 1 },
                new City { Id = 3, Name = "Feke", ProvinceId = 1 },
                new City { Id = 4, Name = "Karaisalı", ProvinceId = 1 },
                new City { Id = 5, Name = "Karataş", ProvinceId = 1 },
                new City { Id = 6, Name = "Kozan", ProvinceId = 1 },
                new City { Id = 7, Name = "Pozantı", ProvinceId = 1 },
                new City { Id = 8, Name = "Saimbeyli", ProvinceId = 1 },
                new City { Id = 9, Name = "Tufanbeyli", ProvinceId = 1 },
                new City { Id = 10, Name = "Yumurtalık", ProvinceId = 1 },
                new City { Id = 11, Name = "Yüreğir", ProvinceId = 1 },
                new City { Id = 12, Name = "Aladağ", ProvinceId = 1 },
                new City { Id = 13, Name = "İmamoğlu", ProvinceId = 1 },
                new City { Id = 14, Name = "Sarıçam", ProvinceId = 1 },
                new City { Id = 15, Name = "Çukurova", ProvinceId = 1 },
                new City { Id = 16, Name = "Adıyaman Merkez", ProvinceId = 2 },
                new City { Id = 17, Name = "Besni", ProvinceId = 2 },
                new City { Id = 18, Name = "Çelikhan", ProvinceId = 2 },
                new City { Id = 19, Name = "Gerger", ProvinceId = 2 },
                new City { Id = 20, Name = "Gölbaşı / Adıyaman", ProvinceId = 2 },
                new City { Id = 21, Name = "Kahta", ProvinceId = 2 },
                new City { Id = 22, Name = "Samsat", ProvinceId = 2 },
                new City { Id = 23, Name = "Sincik", ProvinceId = 2 },
                new City { Id = 24, Name = "Tut", ProvinceId = 2 },
                new City { Id = 25, Name = "Afyonkarahisar Merkez", ProvinceId = 3 },
                new City { Id = 26, Name = "Bolvadin", ProvinceId = 3 },
                new City { Id = 27, Name = "Çay", ProvinceId = 3 },
                new City { Id = 28, Name = "Dazkırı", ProvinceId = 3 },
                new City { Id = 29, Name = "Dinar", ProvinceId = 3 },
                new City { Id = 30, Name = "Emirdağ", ProvinceId = 3 },
                new City { Id = 31, Name = "İhsaniye", ProvinceId = 3 },
                new City { Id = 32, Name = "Sandıklı", ProvinceId = 3 },
                new City { Id = 33, Name = "Sinanpaşa", ProvinceId = 3 },
                new City { Id = 34, Name = "Sultandağı", ProvinceId = 3 },
                new City { Id = 35, Name = "Şuhut", ProvinceId = 3 },
                new City { Id = 36, Name = "Başmakçı", ProvinceId = 3 },
                new City { Id = 37, Name = "Bayat / Afyonkarahisar", ProvinceId = 3 },
                new City { Id = 38, Name = "İscehisar", ProvinceId = 3 },
                new City { Id = 39, Name = "Çobanlar", ProvinceId = 3 },
                new City { Id = 40, Name = "Evciler", ProvinceId = 3 },
                new City { Id = 41, Name = "Hocalar", ProvinceId = 3 },
                new City { Id = 42, Name = "Kızılören", ProvinceId = 3 },
                new City { Id = 43, Name = "Ağrı Merkez", ProvinceId = 4 },
                new City { Id = 44, Name = "Diyadin", ProvinceId = 4 },
                new City { Id = 45, Name = "Doğubayazıt", ProvinceId = 4 },
                new City { Id = 46, Name = "Eleşkirt", ProvinceId = 4 },
                new City { Id = 47, Name = "Hamur", ProvinceId = 4 },
                new City { Id = 48, Name = "Patnos", ProvinceId = 4 },
                new City { Id = 49, Name = "Taşlıçay", ProvinceId = 4 },
                new City { Id = 50, Name = "Tutak", ProvinceId = 4 },
                new City { Id = 51, Name = "Amasya Merkez", ProvinceId = 5 },
                new City { Id = 52, Name = "Göynücek", ProvinceId = 5 },
                new City { Id = 53, Name = "Gümüşhacıköy", ProvinceId = 5 },
                new City { Id = 54, Name = "Merzifon", ProvinceId = 5 },
                new City { Id = 55, Name = "Suluova", ProvinceId = 5 },
                new City { Id = 56, Name = "Taşova", ProvinceId = 5 },
                new City { Id = 57, Name = "Hamamözü", ProvinceId = 5 },
                new City { Id = 58, Name = "Altındağ", ProvinceId = 6 },
                new City { Id = 59, Name = "Ayaş", ProvinceId = 6 },
                new City { Id = 60, Name = "Bala", ProvinceId = 6 },
                new City { Id = 61, Name = "Beypazarı", ProvinceId = 6 },
                new City { Id = 62, Name = "Çamlıdere", ProvinceId = 6 },
                new City { Id = 63, Name = "Çankaya", ProvinceId = 6 },
                new City { Id = 64, Name = "Çubuk", ProvinceId = 6 },
                new City { Id = 65, Name = "Elmadağ", ProvinceId = 6 },
                new City { Id = 66, Name = "Güdül", ProvinceId = 6 },
                new City { Id = 67, Name = "Haymana", ProvinceId = 6 },
                new City { Id = 68, Name = "Kalecik", ProvinceId = 6 },
                new City { Id = 69, Name = "Kızılcahamam", ProvinceId = 6 },
                new City { Id = 70, Name = "Nallıhan", ProvinceId = 6 },
                new City { Id = 71, Name = "Polatlı", ProvinceId = 6 },
                new City { Id = 72, Name = "Şereflikoçhisar", ProvinceId = 6 },
                new City { Id = 73, Name = "Yenimahalle", ProvinceId = 6 },
                new City { Id = 74, Name = "Gölbaşı / Ankara", ProvinceId = 6 },
                new City { Id = 75, Name = "Keçiören", ProvinceId = 6 },
                new City { Id = 76, Name = "Mamak", ProvinceId = 6 },
                new City { Id = 77, Name = "Sincan", ProvinceId = 6 },
                new City { Id = 78, Name = "Kazan", ProvinceId = 6 },
                new City { Id = 79, Name = "Akyurt", ProvinceId = 6 },
                new City { Id = 80, Name = "Etimesgut", ProvinceId = 6 },
                new City { Id = 81, Name = "Evren", ProvinceId = 6 },
                new City { Id = 82, Name = "Pursaklar", ProvinceId = 6 },
                new City { Id = 83, Name = "Akseki", ProvinceId = 7 },
                new City { Id = 84, Name = "Alanya", ProvinceId = 7 },
                new City { Id = 85, Name = "Elmalı", ProvinceId = 7 },
                new City { Id = 86, Name = "Finike", ProvinceId = 7 },
                new City { Id = 87, Name = "Gazipaşa", ProvinceId = 7 },
                new City { Id = 88, Name = "Gündoğmuş", ProvinceId = 7 },
                new City { Id = 89, Name = "Kaş", ProvinceId = 7 },
                new City { Id = 90, Name = "Korkuteli", ProvinceId = 7 },
                new City { Id = 91, Name = "Kumluca", ProvinceId = 7 },
                new City { Id = 92, Name = "Manavgat", ProvinceId = 7 },
                new City { Id = 93, Name = "Serik", ProvinceId = 7 },
                new City { Id = 94, Name = "Demre", ProvinceId = 7 },
                new City { Id = 95, Name = "İbradı", ProvinceId = 7 },
                new City { Id = 96, Name = "Kemer / Antalya", ProvinceId = 7 },
                new City { Id = 97, Name = "Aksu / Antalya", ProvinceId = 7 },
                new City { Id = 98, Name = "Döşemealtı", ProvinceId = 7 },
                new City { Id = 99, Name = "Kepez", ProvinceId = 7 },
                new City { Id = 100, Name = "Konyaaltı", ProvinceId = 7 },
                new City { Id = 101, Name = "Muratpaşa", ProvinceId = 7 },
                new City { Id = 102, Name = "Ardanuç", ProvinceId = 8 },
                new City { Id = 103, Name = "Arhavi", ProvinceId = 8 },
                new City { Id = 104, Name = "Artvin Merkez", ProvinceId = 8 },
                new City { Id = 105, Name = "Borçka", ProvinceId = 8 },
                new City { Id = 106, Name = "Hopa", ProvinceId = 8 },
                new City { Id = 107, Name = "Şavşat", ProvinceId = 8 },
                new City { Id = 108, Name = "Yusufeli", ProvinceId = 8 },
                new City { Id = 109, Name = "Murgul", ProvinceId = 8 },
                new City { Id = 110, Name = "Bozdoğan", ProvinceId = 9 },
                new City { Id = 111, Name = "Çine", ProvinceId = 9 },
                new City { Id = 112, Name = "Germencik", ProvinceId = 9 },
                new City { Id = 113, Name = "Karacasu", ProvinceId = 9 },
                new City { Id = 114, Name = "Koçarlı", ProvinceId = 9 },
                new City { Id = 115, Name = "Kuşadası", ProvinceId = 9 },
                new City { Id = 116, Name = "Kuyucak", ProvinceId = 9 },
                new City { Id = 117, Name = "Nazilli", ProvinceId = 9 },
                new City { Id = 118, Name = "Söke", ProvinceId = 9 },
                new City { Id = 119, Name = "Sultanhisar", ProvinceId = 9 },
                new City { Id = 120, Name = "Yenipazar / Aydın", ProvinceId = 9 },
                new City { Id = 121, Name = "Buharkent", ProvinceId = 9 },
                new City { Id = 122, Name = "İncirliova", ProvinceId = 9 },
                new City { Id = 123, Name = "Karpuzlu", ProvinceId = 9 },
                new City { Id = 124, Name = "Köşk", ProvinceId = 9 },
                new City { Id = 125, Name = "Didim", ProvinceId = 9 },
                new City { Id = 126, Name = "Efeler", ProvinceId = 9 },
                new City { Id = 127, Name = "Ayvalık", ProvinceId = 10 },
                new City { Id = 128, Name = "Balya", ProvinceId = 10 },
                new City { Id = 129, Name = "Bandırma", ProvinceId = 10 },
                new City { Id = 130, Name = "Bigadiç", ProvinceId = 10 },
                new City { Id = 131, Name = "Burhaniye", ProvinceId = 10 },
                new City { Id = 132, Name = "Dursunbey", ProvinceId = 10 },
                new City { Id = 133, Name = "Edremit / Balıkesir", ProvinceId = 10 },
                new City { Id = 134, Name = "Erdek", ProvinceId = 10 },
                new City { Id = 135, Name = "Gönen / Balıkesir", ProvinceId = 10 },
                new City { Id = 136, Name = "Havran", ProvinceId = 10 },
                new City { Id = 137, Name = "İvrindi", ProvinceId = 10 },
                new City { Id = 138, Name = "Kepsut", ProvinceId = 10 },
                new City { Id = 139, Name = "Manyas", ProvinceId = 10 },
                new City { Id = 140, Name = "Savaştepe", ProvinceId = 10 },
                new City { Id = 141, Name = "Sındırgı", ProvinceId = 10 },
                new City { Id = 142, Name = "Susurluk", ProvinceId = 10 },
                new City { Id = 143, Name = "Marmara", ProvinceId = 10 },
                new City { Id = 144, Name = "Gömeç", ProvinceId = 10 },
                new City { Id = 145, Name = "Altıeylül", ProvinceId = 10 },
                new City { Id = 146, Name = "Karesi", ProvinceId = 10 },
                new City { Id = 147, Name = "Bilecik Merkez", ProvinceId = 11 },
                new City { Id = 148, Name = "Bozüyük", ProvinceId = 11 },
                new City { Id = 149, Name = "Gölpazarı", ProvinceId = 11 },
                new City { Id = 150, Name = "Osmaneli", ProvinceId = 11 },
                new City { Id = 151, Name = "Pazaryeri", ProvinceId = 11 },
                new City { Id = 152, Name = "Söğüt", ProvinceId = 11 },
                new City { Id = 153, Name = "Yenipazar / Bilecik", ProvinceId = 11 },
                new City { Id = 154, Name = "İnhisar", ProvinceId = 11 },
                new City { Id = 155, Name = "Bingöl Merkez", ProvinceId = 12 },
                new City { Id = 156, Name = "Genç", ProvinceId = 12 },
                new City { Id = 157, Name = "Karlıova", ProvinceId = 12 },
                new City { Id = 158, Name = "Kiğı", ProvinceId = 12 },
                new City { Id = 159, Name = "Solhan", ProvinceId = 12 },
                new City { Id = 160, Name = "Adaklı", ProvinceId = 12 },
                new City { Id = 161, Name = "Yayladere", ProvinceId = 12 },
                new City { Id = 162, Name = "Yedisu", ProvinceId = 12 },
                new City { Id = 163, Name = "Adilcevaz", ProvinceId = 13 },
                new City { Id = 164, Name = "Ahlat", ProvinceId = 13 },
                new City { Id = 165, Name = "Bitlis Merkez", ProvinceId = 13 },
                new City { Id = 166, Name = "Hizan", ProvinceId = 13 },
                new City { Id = 167, Name = "Mutki", ProvinceId = 13 },
                new City { Id = 168, Name = "Tatvan", ProvinceId = 13 },
                new City { Id = 169, Name = "Güroymak", ProvinceId = 13 },
                new City { Id = 170, Name = "Bolu Merkez", ProvinceId = 14 },
                new City { Id = 171, Name = "Gerede", ProvinceId = 14 },
                new City { Id = 172, Name = "Göynük", ProvinceId = 14 },
                new City { Id = 173, Name = "Kıbrıscık", ProvinceId = 14 },
                new City { Id = 174, Name = "Mengen", ProvinceId = 14 },
                new City { Id = 175, Name = "Mudurnu", ProvinceId = 14 },
                new City { Id = 176, Name = "Seben", ProvinceId = 14 },
                new City { Id = 177, Name = "Dörtdivan", ProvinceId = 14 },
                new City { Id = 178, Name = "Yeniçağa", ProvinceId = 14 },
                new City { Id = 179, Name = "Ağlasun", ProvinceId = 15 },
                new City { Id = 180, Name = "Bucak", ProvinceId = 15 },
                new City { Id = 181, Name = "Burdur Merkez", ProvinceId = 15 },
                new City { Id = 182, Name = "Gölhisar", ProvinceId = 15 },
                new City { Id = 183, Name = "Tefenni", ProvinceId = 15 },
                new City { Id = 184, Name = "Yeşilova", ProvinceId = 15 },
                new City { Id = 185, Name = "Karamanlı", ProvinceId = 15 },
                new City { Id = 186, Name = "Kemer / Burdur", ProvinceId = 15 },
                new City { Id = 187, Name = "Altınyayla / Burdur", ProvinceId = 15 },
                new City { Id = 188, Name = "Çavdır", ProvinceId = 15 },
                new City { Id = 189, Name = "Çeltikçi", ProvinceId = 15 },
                new City { Id = 190, Name = "Gemlik", ProvinceId = 16 },
                new City { Id = 191, Name = "İnegöl", ProvinceId = 16 },
                new City { Id = 192, Name = "İznik", ProvinceId = 16 },
                new City { Id = 193, Name = "Karacabey", ProvinceId = 16 },
                new City { Id = 194, Name = "Keles", ProvinceId = 16 },
                new City { Id = 195, Name = "Mudanya", ProvinceId = 16 },
                new City { Id = 196, Name = "Mustafakemalpaşa", ProvinceId = 16 },
                new City { Id = 197, Name = "Orhaneli", ProvinceId = 16 },
                new City { Id = 198, Name = "Orhangazi", ProvinceId = 16 },
                new City { Id = 199, Name = "Yenişehir / Bursa", ProvinceId = 16 },
                new City { Id = 200, Name = "Büyükorhan", ProvinceId = 16 },
                new City { Id = 201, Name = "Harmancık", ProvinceId = 16 },
                new City { Id = 202, Name = "Nilüfer", ProvinceId = 16 },
                new City { Id = 203, Name = "Osmangazi", ProvinceId = 16 },
                new City { Id = 204, Name = "Yıldırım", ProvinceId = 16 },
                new City { Id = 205, Name = "Gürsu", ProvinceId = 16 },
                new City { Id = 206, Name = "Kestel", ProvinceId = 16 },
                new City { Id = 207, Name = "Ayvacık / Çanakkale", ProvinceId = 17 },
                new City { Id = 208, Name = "Bayramiç", ProvinceId = 17 },
                new City { Id = 209, Name = "Biga", ProvinceId = 17 },
                new City { Id = 210, Name = "Bozcaada", ProvinceId = 17 },
                new City { Id = 211, Name = "Çan", ProvinceId = 17 },
                new City { Id = 212, Name = "Çanakkale Merkez", ProvinceId = 17 },
                new City { Id = 213, Name = "Eceabat", ProvinceId = 17 },
                new City { Id = 214, Name = "Ezine", ProvinceId = 17 },
                new City { Id = 215, Name = "Gelibolu", ProvinceId = 17 },
                new City { Id = 216, Name = "Gökçeada", ProvinceId = 17 },
                new City { Id = 217, Name = "Lapseki", ProvinceId = 17 },
                new City { Id = 218, Name = "Yenice / Çanakkale", ProvinceId = 17 },
                new City { Id = 219, Name = "Çankırı Merkez", ProvinceId = 18 },
                new City { Id = 220, Name = "Çerkeş", ProvinceId = 18 },
                new City { Id = 221, Name = "Eldivan", ProvinceId = 18 },
                new City { Id = 222, Name = "Ilgaz", ProvinceId = 18 },
                new City { Id = 223, Name = "Kurşunlu", ProvinceId = 18 },
                new City { Id = 224, Name = "Orta", ProvinceId = 18 },
                new City { Id = 225, Name = "Şabanözü", ProvinceId = 18 },
                new City { Id = 226, Name = "Yapraklı", ProvinceId = 18 },
                new City { Id = 227, Name = "Atkaracalar", ProvinceId = 18 },
                new City { Id = 228, Name = "Kızılırmak", ProvinceId = 18 },
                new City { Id = 229, Name = "Bayramören", ProvinceId = 18 },
                new City { Id = 230, Name = "Korgun", ProvinceId = 18 },
                new City { Id = 231, Name = "Alaca", ProvinceId = 19 },
                new City { Id = 232, Name = "Bayat / Çorum", ProvinceId = 19 },
                new City { Id = 233, Name = "Çorum Merkez", ProvinceId = 19 },
                new City { Id = 234, Name = "İskilip", ProvinceId = 19 },
                new City { Id = 235, Name = "Kargı", ProvinceId = 19 },
                new City { Id = 236, Name = "Mecitözü", ProvinceId = 19 },
                new City { Id = 237, Name = "Ortaköy / Çorum", ProvinceId = 19 },
                new City { Id = 238, Name = "Osmancık", ProvinceId = 19 },
                new City { Id = 239, Name = "Sungurlu", ProvinceId = 19 },
                new City { Id = 240, Name = "Boğazkale", ProvinceId = 19 },
                new City { Id = 241, Name = "Uğurludağ", ProvinceId = 19 },
                new City { Id = 242, Name = "Dodurga", ProvinceId = 19 },
                new City { Id = 243, Name = "Laçin", ProvinceId = 19 },
                new City { Id = 244, Name = "Oğuzlar", ProvinceId = 19 },
                new City { Id = 245, Name = "Acıpayam", ProvinceId = 20 },
                new City { Id = 246, Name = "Buldan", ProvinceId = 20 },
                new City { Id = 247, Name = "Çal", ProvinceId = 20 },
                new City { Id = 248, Name = "Çameli", ProvinceId = 20 },
                new City { Id = 249, Name = "Çardak", ProvinceId = 20 },
                new City { Id = 250, Name = "Çivril", ProvinceId = 20 },
                new City { Id = 251, Name = "Güney", ProvinceId = 20 },
                new City { Id = 252, Name = "Kale / Denizli", ProvinceId = 20 },
                new City { Id = 253, Name = "Sarayköy", ProvinceId = 20 },
                new City { Id = 254, Name = "Tavas", ProvinceId = 20 },
                new City { Id = 255, Name = "Babadağ", ProvinceId = 20 },
                new City { Id = 256, Name = "Bekilli", ProvinceId = 20 },
                new City { Id = 257, Name = "Honaz", ProvinceId = 20 },
                new City { Id = 258, Name = "Serinhisar", ProvinceId = 20 },
                new City { Id = 259, Name = "Pamukkale", ProvinceId = 20 },
                new City { Id = 260, Name = "Baklan", ProvinceId = 20 },
                new City { Id = 261, Name = "Beyağaç", ProvinceId = 20 },
                new City { Id = 262, Name = "Bozkurt / Denizli", ProvinceId = 20 },
                new City { Id = 263, Name = "Merkezefendi", ProvinceId = 20 },
                new City { Id = 264, Name = "Bismil", ProvinceId = 21 },
                new City { Id = 265, Name = "Çermik", ProvinceId = 21 },
                new City { Id = 266, Name = "Çınar", ProvinceId = 21 },
                new City { Id = 267, Name = "Çüngüş", ProvinceId = 21 },
                new City { Id = 268, Name = "Dicle", ProvinceId = 21 },
                new City { Id = 269, Name = "Ergani", ProvinceId = 21 },
                new City { Id = 270, Name = "Hani", ProvinceId = 21 },
                new City { Id = 271, Name = "Hazro", ProvinceId = 21 },
                new City { Id = 272, Name = "Kulp", ProvinceId = 21 },
                new City { Id = 273, Name = "Lice", ProvinceId = 21 },
                new City { Id = 274, Name = "Silvan", ProvinceId = 21 },
                new City { Id = 275, Name = "Eğil", ProvinceId = 21 },
                new City { Id = 276, Name = "Kocaköy", ProvinceId = 21 },
                new City { Id = 277, Name = "Bağlar", ProvinceId = 21 },
                new City { Id = 278, Name = "Kayapınar", ProvinceId = 21 },
                new City { Id = 279, Name = "Sur", ProvinceId = 21 },
                new City { Id = 280, Name = "Yenişehir / Diyarbakır", ProvinceId = 21 },
                new City { Id = 281, Name = "Edirne Merkez", ProvinceId = 22 },
                new City { Id = 282, Name = "Enez", ProvinceId = 22 },
                new City { Id = 283, Name = "Havsa", ProvinceId = 22 },
                new City { Id = 284, Name = "İpsala", ProvinceId = 22 },
                new City { Id = 285, Name = "Keşan", ProvinceId = 22 },
                new City { Id = 286, Name = "Lalapaşa", ProvinceId = 22 },
                new City { Id = 287, Name = "Meriç", ProvinceId = 22 },
                new City { Id = 288, Name = "Uzunköprü", ProvinceId = 22 },
                new City { Id = 289, Name = "Süloğlu", ProvinceId = 22 },
                new City { Id = 290, Name = "Ağın", ProvinceId = 23 },
                new City { Id = 291, Name = "Baskil", ProvinceId = 23 },
                new City { Id = 292, Name = "Elazığ Merkez", ProvinceId = 23 },
                new City { Id = 293, Name = "Karakoçan", ProvinceId = 23 },
                new City { Id = 294, Name = "Keban", ProvinceId = 23 },
                new City { Id = 295, Name = "Maden", ProvinceId = 23 },
                new City { Id = 296, Name = "Palu", ProvinceId = 23 },
                new City { Id = 297, Name = "Sivrice", ProvinceId = 23 },
                new City { Id = 298, Name = "Arıcak", ProvinceId = 23 },
                new City { Id = 299, Name = "Kovancılar", ProvinceId = 23 },
                new City { Id = 300, Name = "Alacakaya", ProvinceId = 23 },
                new City { Id = 301, Name = "Çayırlı", ProvinceId = 24 },
                new City { Id = 302, Name = "Erzincan Merkez", ProvinceId = 24 },
                new City { Id = 303, Name = "İliç", ProvinceId = 24 },
                new City { Id = 304, Name = "Kemah", ProvinceId = 24 },
                new City { Id = 305, Name = "Kemaliye", ProvinceId = 24 },
                new City { Id = 306, Name = "Refahiye", ProvinceId = 24 },
                new City { Id = 307, Name = "Tercan", ProvinceId = 24 },
                new City { Id = 308, Name = "Üzümlü", ProvinceId = 24 },
                new City { Id = 309, Name = "Otlukbeli", ProvinceId = 24 },
                new City { Id = 310, Name = "Aşkale", ProvinceId = 25 },
                new City { Id = 311, Name = "Çat", ProvinceId = 25 },
                new City { Id = 312, Name = "Hınıs", ProvinceId = 25 },
                new City { Id = 313, Name = "Horasan", ProvinceId = 25 },
                new City { Id = 314, Name = "İspir", ProvinceId = 25 },
                new City { Id = 315, Name = "Karayazı", ProvinceId = 25 },
                new City { Id = 316, Name = "Narman", ProvinceId = 25 },
                new City { Id = 317, Name = "Oltu", ProvinceId = 25 },
                new City { Id = 318, Name = "Olur", ProvinceId = 25 },
                new City { Id = 319, Name = "Pasinler", ProvinceId = 25 },
                new City { Id = 320, Name = "Şenkaya", ProvinceId = 25 },
                new City { Id = 321, Name = "Tekman", ProvinceId = 25 },
                new City { Id = 322, Name = "Tortum", ProvinceId = 25 },
                new City { Id = 323, Name = "Karaçoban", ProvinceId = 25 },
                new City { Id = 324, Name = "Uzundere", ProvinceId = 25 },
                new City { Id = 325, Name = "Pazaryolu", ProvinceId = 25 },
                new City { Id = 326, Name = "Aziziye", ProvinceId = 25 },
                new City { Id = 327, Name = "Köprüköy", ProvinceId = 25 },
                new City { Id = 328, Name = "Palandöken", ProvinceId = 25 },
                new City { Id = 329, Name = "Yakutiye", ProvinceId = 25 },
                new City { Id = 330, Name = "Çifteler", ProvinceId = 26 },
                new City { Id = 331, Name = "Mahmudiye", ProvinceId = 26 },
                new City { Id = 332, Name = "Mihalıççık", ProvinceId = 26 },
                new City { Id = 333, Name = "Sarıcakaya", ProvinceId = 26 },
                new City { Id = 334, Name = "Seyitgazi", ProvinceId = 26 },
                new City { Id = 335, Name = "Sivrihisar", ProvinceId = 26 },
                new City { Id = 336, Name = "Alpu", ProvinceId = 26 },
                new City { Id = 337, Name = "Beylikova", ProvinceId = 26 },
                new City { Id = 338, Name = "İnönü", ProvinceId = 26 },
                new City { Id = 339, Name = "Günyüzü", ProvinceId = 26 },
                new City { Id = 340, Name = "Han", ProvinceId = 26 },
                new City { Id = 341, Name = "Mihalgazi", ProvinceId = 26 },
                new City { Id = 342, Name = "Odunpazarı", ProvinceId = 26 },
                new City { Id = 343, Name = "Tepebaşı", ProvinceId = 26 },
                new City { Id = 344, Name = "Araban", ProvinceId = 27 },
                new City { Id = 345, Name = "İslahiye", ProvinceId = 27 },
                new City { Id = 346, Name = "Nizip", ProvinceId = 27 },
                new City { Id = 347, Name = "Oğuzeli", ProvinceId = 27 },
                new City { Id = 348, Name = "Yavuzeli", ProvinceId = 27 },
                new City { Id = 349, Name = "Şahinbey", ProvinceId = 27 },
                new City { Id = 350, Name = "Şehitkamil", ProvinceId = 27 },
                new City { Id = 351, Name = "Karkamış", ProvinceId = 27 },
                new City { Id = 352, Name = "Nurdağı", ProvinceId = 27 },
                new City { Id = 353, Name = "Alucra", ProvinceId = 28 },
                new City { Id = 354, Name = "Bulancak", ProvinceId = 28 },
                new City { Id = 355, Name = "Dereli", ProvinceId = 28 },
                new City { Id = 356, Name = "Espiye", ProvinceId = 28 },
                new City { Id = 357, Name = "Eynesil", ProvinceId = 28 },
                new City { Id = 358, Name = "Giresun Merkez", ProvinceId = 28 },
                new City { Id = 359, Name = "Görele", ProvinceId = 28 },
                new City { Id = 360, Name = "Keşap", ProvinceId = 28 },
                new City { Id = 361, Name = "Şebinkarahisar", ProvinceId = 28 },
                new City { Id = 362, Name = "Tirebolu", ProvinceId = 28 },
                new City { Id = 363, Name = "Piraziz", ProvinceId = 28 },
                new City { Id = 364, Name = "Yağlıdere", ProvinceId = 28 },
                new City { Id = 365, Name = "Çamoluk", ProvinceId = 28 },
                new City { Id = 366, Name = "Çanakçı", ProvinceId = 28 },
                new City { Id = 367, Name = "Doğankent", ProvinceId = 28 },
                new City { Id = 368, Name = "Güce", ProvinceId = 28 },
                new City { Id = 369, Name = "Gümüşhane Merkez", ProvinceId = 29 },
                new City { Id = 370, Name = "Kelkit", ProvinceId = 29 },
                new City { Id = 371, Name = "Şiran", ProvinceId = 29 },
                new City { Id = 372, Name = "Torul", ProvinceId = 29 },
                new City { Id = 373, Name = "Köse", ProvinceId = 29 },
                new City { Id = 374, Name = "Kürtün", ProvinceId = 29 },
                new City { Id = 375, Name = "Çukurca", ProvinceId = 30 },
                new City { Id = 376, Name = "Hakkari Merkez", ProvinceId = 30 },
                new City { Id = 377, Name = "Şemdinli", ProvinceId = 30 },
                new City { Id = 378, Name = "Yüksekova", ProvinceId = 30 },
                new City { Id = 379, Name = "Altınözü", ProvinceId = 31 },
                new City { Id = 380, Name = "Dörtyol", ProvinceId = 31 },
                new City { Id = 381, Name = "Hassa", ProvinceId = 31 },
                new City { Id = 382, Name = "İskenderun", ProvinceId = 31 },
                new City { Id = 383, Name = "Kırıkhan", ProvinceId = 31 },
                new City { Id = 384, Name = "Reyhanlı", ProvinceId = 31 },
                new City { Id = 385, Name = "Samandağ", ProvinceId = 31 },
                new City { Id = 386, Name = "Yayladağı", ProvinceId = 31 },
                new City { Id = 387, Name = "Erzin", ProvinceId = 31 },
                new City { Id = 388, Name = "Belen", ProvinceId = 31 },
                new City { Id = 389, Name = "Kumlu", ProvinceId = 31 },
                new City { Id = 390, Name = "Antakya", ProvinceId = 31 },
                new City { Id = 391, Name = "Arsuz", ProvinceId = 31 },
                new City { Id = 392, Name = "Defne", ProvinceId = 31 },
                new City { Id = 393, Name = "Payas", ProvinceId = 31 },
                new City { Id = 394, Name = "Atabey", ProvinceId = 32 },
                new City { Id = 395, Name = "Eğirdir", ProvinceId = 32 },
                new City { Id = 396, Name = "Gelendost", ProvinceId = 32 },
                new City { Id = 397, Name = "Isparta Merkez", ProvinceId = 32 },
                new City { Id = 398, Name = "Keçiborlu", ProvinceId = 32 },
                new City { Id = 399, Name = "Senirkent", ProvinceId = 32 },
                new City { Id = 400, Name = "Sütçüler", ProvinceId = 32 },
                new City { Id = 401, Name = "Şarkikaraağaç", ProvinceId = 32 },
                new City { Id = 402, Name = "Uluborlu", ProvinceId = 32 },
                new City { Id = 403, Name = "Yalvaç", ProvinceId = 32 },
                new City { Id = 404, Name = "Aksu / Isparta", ProvinceId = 32 },
                new City { Id = 405, Name = "Gönen / Isparta", ProvinceId = 32 },
                new City { Id = 406, Name = "Yenişarbademli", ProvinceId = 32 },
                new City { Id = 407, Name = "Anamur", ProvinceId = 33 },
                new City { Id = 408, Name = "Erdemli", ProvinceId = 33 },
                new City { Id = 409, Name = "Gülnar", ProvinceId = 33 },
                new City { Id = 410, Name = "Mut", ProvinceId = 33 },
                new City { Id = 411, Name = "Silifke", ProvinceId = 33 },
                new City { Id = 412, Name = "Tarsus", ProvinceId = 33 },
                new City { Id = 413, Name = "Aydıncık / Mersin", ProvinceId = 33 },
                new City { Id = 414, Name = "Bozyazı", ProvinceId = 33 },
                new City { Id = 415, Name = "Çamlıyayla", ProvinceId = 33 },
                new City { Id = 416, Name = "Akdeniz", ProvinceId = 33 },
                new City { Id = 417, Name = "Mezitli", ProvinceId = 33 },
                new City { Id = 418, Name = "Toroslar", ProvinceId = 33 },
                new City { Id = 419, Name = "Yenişehir / Mersin", ProvinceId = 33 },
                new City { Id = 420, Name = "Adalar", ProvinceId = 34 },
                new City { Id = 421, Name = "Bakırköy", ProvinceId = 34 },
                new City { Id = 422, Name = "Beşiktaş", ProvinceId = 34 },
                new City { Id = 423, Name = "Beykoz", ProvinceId = 34 },
                new City { Id = 424, Name = "Beyoğlu", ProvinceId = 34 },
                new City { Id = 425, Name = "Çatalca", ProvinceId = 34 },
                new City { Id = 426, Name = "Eyüp", ProvinceId = 34 },
                new City { Id = 427, Name = "Fatih", ProvinceId = 34 },
                new City { Id = 428, Name = "Gaziosmanpaşa", ProvinceId = 34 },
                new City { Id = 429, Name = "Kadıköy", ProvinceId = 34 },
                new City { Id = 430, Name = "Kartal", ProvinceId = 34 },
                new City { Id = 431, Name = "Sarıyer", ProvinceId = 34 },
                new City { Id = 432, Name = "Silivri", ProvinceId = 34 },
                new City { Id = 433, Name = "Şile", ProvinceId = 34 },
                new City { Id = 434, Name = "Şişli", ProvinceId = 34 },
                new City { Id = 435, Name = "Üsküdar", ProvinceId = 34 },
                new City { Id = 436, Name = "Zeytinburnu", ProvinceId = 34 },
                new City { Id = 437, Name = "Büyükçekmece", ProvinceId = 34 },
                new City { Id = 438, Name = "Kağıthane", ProvinceId = 34 },
                new City { Id = 439, Name = "Küçükçekmece", ProvinceId = 34 },
                new City { Id = 440, Name = "Pendik", ProvinceId = 34 },
                new City { Id = 441, Name = "Ümraniye", ProvinceId = 34 },
                new City { Id = 442, Name = "Bayrampaşa", ProvinceId = 34 },
                new City { Id = 443, Name = "Avcılar", ProvinceId = 34 },
                new City { Id = 444, Name = "Bağcılar", ProvinceId = 34 },
                new City { Id = 445, Name = "Bahçelievler", ProvinceId = 34 },
                new City { Id = 446, Name = "Güngören", ProvinceId = 34 },
                new City { Id = 447, Name = "Maltepe", ProvinceId = 34 },
                new City { Id = 448, Name = "Sultanbeyli", ProvinceId = 34 },
                new City { Id = 449, Name = "Tuzla", ProvinceId = 34 },
                new City { Id = 450, Name = "Esenler", ProvinceId = 34 },
                new City { Id = 451, Name = "Arnavutköy", ProvinceId = 34 },
                new City { Id = 452, Name = "Ataşehir", ProvinceId = 34 },
                new City { Id = 453, Name = "Başakşehir", ProvinceId = 34 },
                new City { Id = 454, Name = "Beylikdüzü", ProvinceId = 34 },
                new City { Id = 455, Name = "Çekmeköy", ProvinceId = 34 },
                new City { Id = 456, Name = "Esenyurt", ProvinceId = 34 },
                new City { Id = 457, Name = "Sancaktepe", ProvinceId = 34 },
                new City { Id = 458, Name = "Sultangazi", ProvinceId = 34 },
                new City { Id = 459, Name = "Aliağa", ProvinceId = 35 },
                new City { Id = 460, Name = "Bayındır", ProvinceId = 35 },
                new City { Id = 461, Name = "Bergama", ProvinceId = 35 },
                new City { Id = 462, Name = "Bornova", ProvinceId = 35 },
                new City { Id = 463, Name = "Çeşme", ProvinceId = 35 },
                new City { Id = 464, Name = "Dikili", ProvinceId = 35 },
                new City { Id = 465, Name = "Foça", ProvinceId = 35 },
                new City { Id = 466, Name = "Karaburun", ProvinceId = 35 },
                new City { Id = 467, Name = "Karşıyaka", ProvinceId = 35 },
                new City { Id = 468, Name = "Kemalpaşa / İzmir", ProvinceId = 35 },
                new City { Id = 469, Name = "Kınık", ProvinceId = 35 },
                new City { Id = 470, Name = "Kiraz", ProvinceId = 35 },
                new City { Id = 471, Name = "Menemen", ProvinceId = 35 },
                new City { Id = 472, Name = "Ödemiş", ProvinceId = 35 },
                new City { Id = 473, Name = "Seferihisar", ProvinceId = 35 },
                new City { Id = 474, Name = "Selçuk", ProvinceId = 35 },
                new City { Id = 475, Name = "Tire", ProvinceId = 35 },
                new City { Id = 476, Name = "Torbalı", ProvinceId = 35 },
                new City { Id = 477, Name = "Urla", ProvinceId = 35 },
                new City { Id = 478, Name = "Beydağ", ProvinceId = 35 },
                new City { Id = 479, Name = "Buca", ProvinceId = 35 },
                new City { Id = 480, Name = "Konak", ProvinceId = 35 },
                new City { Id = 481, Name = "Menderes", ProvinceId = 35 },
                new City { Id = 482, Name = "Balçova", ProvinceId = 35 },
                new City { Id = 483, Name = "Çiğli", ProvinceId = 35 },
                new City { Id = 484, Name = "Gaziemir", ProvinceId = 35 },
                new City { Id = 485, Name = "Narlıdere", ProvinceId = 35 },
                new City { Id = 486, Name = "Güzelbahçe", ProvinceId = 35 },
                new City { Id = 487, Name = "Bayraklı", ProvinceId = 35 },
                new City { Id = 488, Name = "Karabağlar", ProvinceId = 35 },
                new City { Id = 489, Name = "Arpaçay", ProvinceId = 36 },
                new City { Id = 490, Name = "Digor", ProvinceId = 36 },
                new City { Id = 491, Name = "Kağızman", ProvinceId = 36 },
                new City { Id = 492, Name = "Kars Merkez", ProvinceId = 36 },
                new City { Id = 493, Name = "Sarıkamış", ProvinceId = 36 },
                new City { Id = 494, Name = "Selim", ProvinceId = 36 },
                new City { Id = 495, Name = "Susuz", ProvinceId = 36 },
                new City { Id = 496, Name = "Akyaka", ProvinceId = 36 },
                new City { Id = 497, Name = "Abana", ProvinceId = 37 },
                new City { Id = 498, Name = "Araç", ProvinceId = 37 },
                new City { Id = 499, Name = "Azdavay", ProvinceId = 37 },
                new City { Id = 500, Name = "Bozkurt / Kastamonu", ProvinceId = 37 },
                new City { Id = 501, Name = "Cide", ProvinceId = 37 },
                new City { Id = 502, Name = "Çatalzeytin", ProvinceId = 37 },
                new City { Id = 503, Name = "Daday", ProvinceId = 37 },
                new City { Id = 504, Name = "Devrekani", ProvinceId = 37 },
                new City { Id = 505, Name = "İnebolu", ProvinceId = 37 },
                new City { Id = 506, Name = "Kastamonu Merkez", ProvinceId = 37 },
                new City { Id = 507, Name = "Küre", ProvinceId = 37 },
                new City { Id = 508, Name = "Taşköprü", ProvinceId = 37 },
                new City { Id = 509, Name = "Tosya", ProvinceId = 37 },
                new City { Id = 510, Name = "İhsangazi", ProvinceId = 37 },
                new City { Id = 511, Name = "Pınarbaşı / Kastamonu", ProvinceId = 37 },
                new City { Id = 512, Name = "Şenpazar", ProvinceId = 37 },
                new City { Id = 513, Name = "Ağlı", ProvinceId = 37 },
                new City { Id = 514, Name = "Doğanyurt", ProvinceId = 37 },
                new City { Id = 515, Name = "Hanönü", ProvinceId = 37 },
                new City { Id = 516, Name = "Seydiler", ProvinceId = 37 },
                new City { Id = 517, Name = "Bünyan", ProvinceId = 38 },
                new City { Id = 518, Name = "Develi", ProvinceId = 38 },
                new City { Id = 519, Name = "Felahiye", ProvinceId = 38 },
                new City { Id = 520, Name = "İncesu", ProvinceId = 38 },
                new City { Id = 521, Name = "Pınarbaşı / Kayseri", ProvinceId = 38 },
                new City { Id = 522, Name = "Sarıoğlan", ProvinceId = 38 },
                new City { Id = 523, Name = "Sarız", ProvinceId = 38 },
                new City { Id = 524, Name = "Tomarza", ProvinceId = 38 },
                new City { Id = 525, Name = "Yahyalı", ProvinceId = 38 },
                new City { Id = 526, Name = "Yeşilhisar", ProvinceId = 38 },
                new City { Id = 527, Name = "Akkışla", ProvinceId = 38 },
                new City { Id = 528, Name = "Talas", ProvinceId = 38 },
                new City { Id = 529, Name = "Kocasinan", ProvinceId = 38 },
                new City { Id = 530, Name = "Melikgazi", ProvinceId = 38 },
                new City { Id = 531, Name = "Hacılar", ProvinceId = 38 },
                new City { Id = 532, Name = "Özvatan", ProvinceId = 38 },
                new City { Id = 533, Name = "Babaeski", ProvinceId = 39 },
                new City { Id = 534, Name = "Demirköy", ProvinceId = 39 },
                new City { Id = 535, Name = "Kırklareli Merkez", ProvinceId = 39 },
                new City { Id = 536, Name = "Kofçaz", ProvinceId = 39 },
                new City { Id = 537, Name = "Lüleburgaz", ProvinceId = 39 },
                new City { Id = 538, Name = "Pehlivanköy", ProvinceId = 39 },
                new City { Id = 539, Name = "Pınarhisar", ProvinceId = 39 },
                new City { Id = 540, Name = "Vize", ProvinceId = 39 },
                new City { Id = 541, Name = "Çiçekdağı", ProvinceId = 40 },
                new City { Id = 542, Name = "Kaman", ProvinceId = 40 },
                new City { Id = 543, Name = "Kırşehir Merkez", ProvinceId = 40 },
                new City { Id = 544, Name = "Mucur", ProvinceId = 40 },
                new City { Id = 545, Name = "Akpınar", ProvinceId = 40 },
                new City { Id = 546, Name = "Akçakent", ProvinceId = 40 },
                new City { Id = 547, Name = "Boztepe", ProvinceId = 40 },
                new City { Id = 548, Name = "Gebze", ProvinceId = 41 },
                new City { Id = 549, Name = "Gölcük", ProvinceId = 41 },
                new City { Id = 550, Name = "Kandıra", ProvinceId = 41 },
                new City { Id = 551, Name = "Karamürsel", ProvinceId = 41 },
                new City { Id = 552, Name = "Körfez", ProvinceId = 41 },
                new City { Id = 553, Name = "Derince", ProvinceId = 41 },
                new City { Id = 554, Name = "Başiskele", ProvinceId = 41 },
                new City { Id = 555, Name = "Çayırova", ProvinceId = 41 },
                new City { Id = 556, Name = "Darıca", ProvinceId = 41 },
                new City { Id = 557, Name = "Dilovası", ProvinceId = 41 },
                new City { Id = 558, Name = "İzmit", ProvinceId = 41 },
                new City { Id = 559, Name = "Kartepe", ProvinceId = 41 },
                new City { Id = 560, Name = "Akşehir", ProvinceId = 42 },
                new City { Id = 561, Name = "Beyşehir", ProvinceId = 42 },
                new City { Id = 562, Name = "Bozkır", ProvinceId = 42 },
                new City { Id = 563, Name = "Cihanbeyli", ProvinceId = 42 },
                new City { Id = 564, Name = "Çumra", ProvinceId = 42 },
                new City { Id = 565, Name = "Doğanhisar", ProvinceId = 42 },
                new City { Id = 566, Name = "Ereğli / Konya", ProvinceId = 42 },
                new City { Id = 567, Name = "Hadim", ProvinceId = 42 },
                new City { Id = 568, Name = "Ilgın", ProvinceId = 42 },
                new City { Id = 569, Name = "Kadınhanı", ProvinceId = 42 },
                new City { Id = 570, Name = "Karapınar", ProvinceId = 42 },
                new City { Id = 571, Name = "Kulu", ProvinceId = 42 },
                new City { Id = 572, Name = "Sarayönü", ProvinceId = 42 },
                new City { Id = 573, Name = "Seydişehir", ProvinceId = 42 },
                new City { Id = 574, Name = "Yunak", ProvinceId = 42 },
                new City { Id = 575, Name = "Akören", ProvinceId = 42 },
                new City { Id = 576, Name = "Altınekin", ProvinceId = 42 },
                new City { Id = 577, Name = "Derebucak", ProvinceId = 42 },
                new City { Id = 578, Name = "Hüyük", ProvinceId = 42 },
                new City { Id = 579, Name = "Karatay", ProvinceId = 42 },
                new City { Id = 580, Name = "Meram", ProvinceId = 42 },
                new City { Id = 581, Name = "Selçuklu", ProvinceId = 42 },
                new City { Id = 582, Name = "Taşkent", ProvinceId = 42 },
                new City { Id = 583, Name = "Ahırlı", ProvinceId = 42 },
                new City { Id = 584, Name = "Çeltik", ProvinceId = 42 },
                new City { Id = 585, Name = "Derbent", ProvinceId = 42 },
                new City { Id = 586, Name = "Emirgazi", ProvinceId = 42 },
                new City { Id = 587, Name = "Güneysınır", ProvinceId = 42 },
                new City { Id = 588, Name = "Halkapınar", ProvinceId = 42 },
                new City { Id = 589, Name = "Tuzlukçu", ProvinceId = 42 },
                new City { Id = 590, Name = "Yalıhüyük", ProvinceId = 42 },
                new City { Id = 591, Name = "Altıntaş", ProvinceId = 43 },
                new City { Id = 592, Name = "Domaniç", ProvinceId = 43 },
                new City { Id = 593, Name = "Emet", ProvinceId = 43 },
                new City { Id = 594, Name = "Gediz", ProvinceId = 43 },
                new City { Id = 595, Name = "Kütahya Merkez", ProvinceId = 43 },
                new City { Id = 596, Name = "Simav", ProvinceId = 43 },
                new City { Id = 597, Name = "Tavşanlı", ProvinceId = 43 },
                new City { Id = 598, Name = "Aslanapa", ProvinceId = 43 },
                new City { Id = 599, Name = "Dumlupınar", ProvinceId = 43 },
                new City { Id = 600, Name = "Hisarcık", ProvinceId = 43 },
                new City { Id = 601, Name = "Şaphane", ProvinceId = 43 },
                new City { Id = 602, Name = "Çavdarhisar", ProvinceId = 43 },
                new City { Id = 603, Name = "Pazarlar", ProvinceId = 43 },
                new City { Id = 604, Name = "Akçadağ", ProvinceId = 44 },
                new City { Id = 605, Name = "Arapgir", ProvinceId = 44 },
                new City { Id = 606, Name = "Arguvan", ProvinceId = 44 },
                new City { Id = 607, Name = "Darende", ProvinceId = 44 },
                new City { Id = 608, Name = "Doğanşehir", ProvinceId = 44 },
                new City { Id = 609, Name = "Hekimhan", ProvinceId = 44 },
                new City { Id = 610, Name = "Pütürge", ProvinceId = 44 },
                new City { Id = 611, Name = "Yeşilyurt / Malatya", ProvinceId = 44 },
                new City { Id = 612, Name = "Battalgazi", ProvinceId = 44 },
                new City { Id = 613, Name = "Doğanyol", ProvinceId = 44 },
                new City { Id = 614, Name = "Kale / Malatya", ProvinceId = 44 },
                new City { Id = 615, Name = "Kuluncak", ProvinceId = 44 },
                new City { Id = 616, Name = "Yazıhan", ProvinceId = 44 },
                new City { Id = 617, Name = "Akhisar", ProvinceId = 45 },
                new City { Id = 618, Name = "Alaşehir", ProvinceId = 45 },
                new City { Id = 619, Name = "Demirci", ProvinceId = 45 },
                new City { Id = 620, Name = "Gördes", ProvinceId = 45 },
                new City { Id = 621, Name = "Kırkağaç", ProvinceId = 45 },
                new City { Id = 622, Name = "Kula", ProvinceId = 45 },
                new City { Id = 623, Name = "Salihli", ProvinceId = 45 },
                new City { Id = 624, Name = "Sarıgöl", ProvinceId = 45 },
                new City { Id = 625, Name = "Saruhanlı", ProvinceId = 45 },
                new City { Id = 626, Name = "Selendi", ProvinceId = 45 },
                new City { Id = 627, Name = "Soma", ProvinceId = 45 },
                new City { Id = 628, Name = "Turgutlu", ProvinceId = 45 },
                new City { Id = 629, Name = "Ahmetli", ProvinceId = 45 },
                new City { Id = 630, Name = "Gölmarmara", ProvinceId = 45 },
                new City { Id = 631, Name = "Köprübaşı / Manisa", ProvinceId = 45 },
                new City { Id = 632, Name = "Şehzadeler", ProvinceId = 45 },
                new City { Id = 633, Name = "Yunusemre", ProvinceId = 45 },
                new City { Id = 634, Name = "Afşin", ProvinceId = 46 },
                new City { Id = 635, Name = "Andırın", ProvinceId = 46 },
                new City { Id = 636, Name = "Elbistan", ProvinceId = 46 },
                new City { Id = 637, Name = "Göksun", ProvinceId = 46 },
                new City { Id = 638, Name = "Pazarcık", ProvinceId = 46 },
                new City { Id = 639, Name = "Türkoğlu", ProvinceId = 46 },
                new City { Id = 640, Name = "Çağlayancerit", ProvinceId = 46 },
                new City { Id = 641, Name = "Ekinözü", ProvinceId = 46 },
                new City { Id = 642, Name = "Nurhak", ProvinceId = 46 },
                new City { Id = 643, Name = "Dulkadiroğlu", ProvinceId = 46 },
                new City { Id = 644, Name = "Onikişubat", ProvinceId = 46 },
                new City { Id = 645, Name = "Derik", ProvinceId = 47 },
                new City { Id = 646, Name = "Kızıltepe", ProvinceId = 47 },
                new City { Id = 647, Name = "Mazıdağı", ProvinceId = 47 },
                new City { Id = 648, Name = "Midyat", ProvinceId = 47 },
                new City { Id = 649, Name = "Nusaybin", ProvinceId = 47 },
                new City { Id = 650, Name = "Ömerli", ProvinceId = 47 },
                new City { Id = 651, Name = "Savur", ProvinceId = 47 },
                new City { Id = 652, Name = "Dargeçit", ProvinceId = 47 },
                new City { Id = 653, Name = "Yeşilli", ProvinceId = 47 },
                new City { Id = 654, Name = "Artuklu", ProvinceId = 47 },
                new City { Id = 655, Name = "Bodrum", ProvinceId = 48 },
                new City { Id = 656, Name = "Datça", ProvinceId = 48 },
                new City { Id = 657, Name = "Fethiye", ProvinceId = 48 },
                new City { Id = 658, Name = "Köyceğiz", ProvinceId = 48 },
                new City { Id = 659, Name = "Marmaris", ProvinceId = 48 },
                new City { Id = 660, Name = "Milas", ProvinceId = 48 },
                new City { Id = 661, Name = "Ula", ProvinceId = 48 },
                new City { Id = 662, Name = "Yatağan", ProvinceId = 48 },
                new City { Id = 663, Name = "Dalaman", ProvinceId = 48 },
                new City { Id = 664, Name = "Ortaca", ProvinceId = 48 },
                new City { Id = 665, Name = "Kavaklıdere", ProvinceId = 48 },
                new City { Id = 666, Name = "Menteşe", ProvinceId = 48 },
                new City { Id = 667, Name = "Seydikemer", ProvinceId = 48 },
                new City { Id = 668, Name = "Bulanık", ProvinceId = 49 },
                new City { Id = 669, Name = "Malazgirt", ProvinceId = 49 },
                new City { Id = 670, Name = "Muş Merkez", ProvinceId = 49 },
                new City { Id = 671, Name = "Varto", ProvinceId = 49 },
                new City { Id = 672, Name = "Hasköy", ProvinceId = 49 },
                new City { Id = 673, Name = "Korkut", ProvinceId = 49 },
                new City { Id = 674, Name = "Avanos", ProvinceId = 50 },
                new City { Id = 675, Name = "Derinkuyu", ProvinceId = 50 },
                new City { Id = 676, Name = "Gülşehir", ProvinceId = 50 },
                new City { Id = 677, Name = "Hacıbektaş", ProvinceId = 50 },
                new City { Id = 678, Name = "Kozaklı", ProvinceId = 50 },
                new City { Id = 679, Name = "Nevşehir Merkez", ProvinceId = 50 },
                new City { Id = 680, Name = "Ürgüp", ProvinceId = 50 },
                new City { Id = 681, Name = "Acıgöl", ProvinceId = 50 },
                new City { Id = 682, Name = "Bor", ProvinceId = 51 },
                new City { Id = 683, Name = "Çamardı", ProvinceId = 51 },
                new City { Id = 684, Name = "Niğde Merkez", ProvinceId = 51 },
                new City { Id = 685, Name = "Ulukışla", ProvinceId = 51 },
                new City { Id = 686, Name = "Altunhisar", ProvinceId = 51 },
                new City { Id = 687, Name = "Çiftlik", ProvinceId = 51 },
                new City { Id = 688, Name = "Akkuş", ProvinceId = 52 },
                new City { Id = 689, Name = "Aybastı", ProvinceId = 52 },
                new City { Id = 690, Name = "Fatsa", ProvinceId = 52 },
                new City { Id = 691, Name = "Gölköy", ProvinceId = 52 },
                new City { Id = 692, Name = "Korgan", ProvinceId = 52 },
                new City { Id = 693, Name = "Kumru", ProvinceId = 52 },
                new City { Id = 694, Name = "Mesudiye", ProvinceId = 52 },
                new City { Id = 695, Name = "Perşembe", ProvinceId = 52 },
                new City { Id = 696, Name = "Ulubey / Ordu", ProvinceId = 52 },
                new City { Id = 697, Name = "Ünye", ProvinceId = 52 },
                new City { Id = 698, Name = "Gülyalı", ProvinceId = 52 },
                new City { Id = 699, Name = "Gürgentepe", ProvinceId = 52 },
                new City { Id = 700, Name = "Çamaş", ProvinceId = 52 },
                new City { Id = 701, Name = "Çatalpınar", ProvinceId = 52 },
                new City { Id = 702, Name = "Çaybaşı", ProvinceId = 52 },
                new City { Id = 703, Name = "İkizce", ProvinceId = 52 },
                new City { Id = 704, Name = "Kabadüz", ProvinceId = 52 },
                new City { Id = 705, Name = "Kabataş", ProvinceId = 52 },
                new City { Id = 706, Name = "Altınordu", ProvinceId = 52 },
                new City { Id = 707, Name = "Ardeşen", ProvinceId = 53 },
                new City { Id = 708, Name = "Çamlıhemşin", ProvinceId = 53 },
                new City { Id = 709, Name = "Çayeli", ProvinceId = 53 },
                new City { Id = 710, Name = "Fındıklı", ProvinceId = 53 },
                new City { Id = 711, Name = "İkizdere", ProvinceId = 53 },
                new City { Id = 712, Name = "Kalkandere", ProvinceId = 53 },
                new City { Id = 713, Name = "Pazar / Rize", ProvinceId = 53 },
                new City { Id = 714, Name = "Rize Merkez", ProvinceId = 53 },
                new City { Id = 715, Name = "Güneysu", ProvinceId = 53 },
                new City { Id = 716, Name = "Derepazarı", ProvinceId = 53 },
                new City { Id = 717, Name = "Hemşin", ProvinceId = 53 },
                new City { Id = 718, Name = "İyidere", ProvinceId = 53 },
                new City { Id = 719, Name = "Akyazı", ProvinceId = 54 },
                new City { Id = 720, Name = "Geyve", ProvinceId = 54 },
                new City { Id = 721, Name = "Hendek", ProvinceId = 54 },
                new City { Id = 722, Name = "Karasu", ProvinceId = 54 },
                new City { Id = 723, Name = "Kaynarca", ProvinceId = 54 },
                new City { Id = 724, Name = "Sapanca", ProvinceId = 54 },
                new City { Id = 725, Name = "Kocaali", ProvinceId = 54 },
                new City { Id = 726, Name = "Pamukova", ProvinceId = 54 },
                new City { Id = 727, Name = "Taraklı", ProvinceId = 54 },
                new City { Id = 728, Name = "Ferizli", ProvinceId = 54 },
                new City { Id = 729, Name = "Karapürçek", ProvinceId = 54 },
                new City { Id = 730, Name = "Söğütlü", ProvinceId = 54 },
                new City { Id = 731, Name = "Adapazarı", ProvinceId = 54 },
                new City { Id = 732, Name = "Arifiye", ProvinceId = 54 },
                new City { Id = 733, Name = "Erenler", ProvinceId = 54 },
                new City { Id = 734, Name = "Serdivan", ProvinceId = 54 },
                new City { Id = 735, Name = "Alaçam", ProvinceId = 55 },
                new City { Id = 736, Name = "Bafra", ProvinceId = 55 },
                new City { Id = 737, Name = "Çarşamba", ProvinceId = 55 },
                new City { Id = 738, Name = "Havza", ProvinceId = 55 },
                new City { Id = 739, Name = "Kavak", ProvinceId = 55 },
                new City { Id = 740, Name = "Ladik", ProvinceId = 55 },
                new City { Id = 741, Name = "Terme", ProvinceId = 55 },
                new City { Id = 742, Name = "Vezirköprü", ProvinceId = 55 },
                new City { Id = 743, Name = "Asarcık", ProvinceId = 55 },
                new City { Id = 744, Name = "43604", ProvinceId = 55 },
                new City { Id = 745, Name = "Salıpazarı", ProvinceId = 55 },
                new City { Id = 746, Name = "Tekkeköy", ProvinceId = 55 },
                new City { Id = 747, Name = "Ayvacık / Samsun", ProvinceId = 55 },
                new City { Id = 748, Name = "Yakakent", ProvinceId = 55 },
                new City { Id = 749, Name = "Atakum", ProvinceId = 55 },
                new City { Id = 750, Name = "Canik", ProvinceId = 55 },
                new City { Id = 751, Name = "İlkadım", ProvinceId = 55 },
                new City { Id = 752, Name = "Baykan", ProvinceId = 56 },
                new City { Id = 753, Name = "Eruh", ProvinceId = 56 },
                new City { Id = 754, Name = "Kurtalan", ProvinceId = 56 },
                new City { Id = 755, Name = "Pervari", ProvinceId = 56 },
                new City { Id = 756, Name = "Siirt Merkez", ProvinceId = 56 },
                new City { Id = 757, Name = "Şirvan", ProvinceId = 56 },
                new City { Id = 758, Name = "Tillo", ProvinceId = 56 },
                new City { Id = 759, Name = "Ayancık", ProvinceId = 57 },
                new City { Id = 760, Name = "Boyabat", ProvinceId = 57 },
                new City { Id = 761, Name = "Durağan", ProvinceId = 57 },
                new City { Id = 762, Name = "Erfelek", ProvinceId = 57 },
                new City { Id = 763, Name = "Gerze", ProvinceId = 57 },
                new City { Id = 764, Name = "Sinop Merkez", ProvinceId = 57 },
                new City { Id = 765, Name = "Türkeli", ProvinceId = 57 },
                new City { Id = 766, Name = "Dikmen", ProvinceId = 57 },
                new City { Id = 767, Name = "Saraydüzü", ProvinceId = 57 },
                new City { Id = 768, Name = "Divriği", ProvinceId = 58 },
                new City { Id = 769, Name = "Gemerek", ProvinceId = 58 },
                new City { Id = 770, Name = "Gürün", ProvinceId = 58 },
                new City { Id = 771, Name = "Hafik", ProvinceId = 58 },
                new City { Id = 772, Name = "İmranlı", ProvinceId = 58 },
                new City { Id = 773, Name = "Kangal", ProvinceId = 58 },
                new City { Id = 774, Name = "Koyulhisar", ProvinceId = 58 },
                new City { Id = 775, Name = "Sivas Merkez", ProvinceId = 58 },
                new City { Id = 776, Name = "Suşehri", ProvinceId = 58 },
                new City { Id = 777, Name = "Şarkışla", ProvinceId = 58 },
                new City { Id = 778, Name = "Yıldızeli", ProvinceId = 58 },
                new City { Id = 779, Name = "Zara", ProvinceId = 58 },
                new City { Id = 780, Name = "Akıncılar", ProvinceId = 58 },
                new City { Id = 781, Name = "Altınyayla / Sivas", ProvinceId = 58 },
                new City { Id = 782, Name = "Doğanşar", ProvinceId = 58 },
                new City { Id = 783, Name = "Gölova", ProvinceId = 58 },
                new City { Id = 784, Name = "Ulaş", ProvinceId = 58 },
                new City { Id = 785, Name = "Çerkezköy", ProvinceId = 59 },
                new City { Id = 786, Name = "Çorlu", ProvinceId = 59 },
                new City { Id = 787, Name = "Hayrabolu", ProvinceId = 59 },
                new City { Id = 788, Name = "Malkara", ProvinceId = 59 },
                new City { Id = 789, Name = "Muratlı", ProvinceId = 59 },
                new City { Id = 790, Name = "Saray / Tekirdağ", ProvinceId = 59 },
                new City { Id = 791, Name = "Şarköy", ProvinceId = 59 },
                new City { Id = 792, Name = "Marmaraereğlisi", ProvinceId = 59 },
                new City { Id = 793, Name = "Ergene", ProvinceId = 59 },
                new City { Id = 794, Name = "Kapaklı", ProvinceId = 59 },
                new City { Id = 795, Name = "Süleymanpaşa", ProvinceId = 59 },
                new City { Id = 796, Name = "Almus", ProvinceId = 60 },
                new City { Id = 797, Name = "Artova", ProvinceId = 60 },
                new City { Id = 798, Name = "Erbaa", ProvinceId = 60 },
                new City { Id = 799, Name = "Niksar", ProvinceId = 60 },
                new City { Id = 800, Name = "Reşadiye", ProvinceId = 60 },
                new City { Id = 801, Name = "Tokat Merkez", ProvinceId = 60 },
                new City { Id = 802, Name = "Turhal", ProvinceId = 60 },
                new City { Id = 803, Name = "Zile", ProvinceId = 60 },
                new City { Id = 804, Name = "Pazar / Tokat", ProvinceId = 60 },
                new City { Id = 805, Name = "Yeşilyurt / Tokat", ProvinceId = 60 },
                new City { Id = 806, Name = "Başçiftlik", ProvinceId = 60 },
                new City { Id = 807, Name = "Sulusaray", ProvinceId = 60 },
                new City { Id = 808, Name = "Akçaabat", ProvinceId = 61 },
                new City { Id = 809, Name = "Araklı", ProvinceId = 61 },
                new City { Id = 810, Name = "Arsin", ProvinceId = 61 },
                new City { Id = 811, Name = "Çaykara", ProvinceId = 61 },
                new City { Id = 812, Name = "Maçka", ProvinceId = 61 },
                new City { Id = 813, Name = "Of", ProvinceId = 61 },
                new City { Id = 814, Name = "Sürmene", ProvinceId = 61 },
                new City { Id = 815, Name = "Tonya", ProvinceId = 61 },
                new City { Id = 816, Name = "Vakfıkebir", ProvinceId = 61 },
                new City { Id = 817, Name = "Yomra", ProvinceId = 61 },
                new City { Id = 818, Name = "Beşikdüzü", ProvinceId = 61 },
                new City { Id = 819, Name = "Şalpazarı", ProvinceId = 61 },
                new City { Id = 820, Name = "Çarşıbaşı", ProvinceId = 61 },
                new City { Id = 821, Name = "Dernekpazarı", ProvinceId = 61 },
                new City { Id = 822, Name = "Düzköy", ProvinceId = 61 },
                new City { Id = 823, Name = "Hayrat", ProvinceId = 61 },
                new City { Id = 824, Name = "Köprübaşı / Trabzon", ProvinceId = 61 },
                new City { Id = 825, Name = "Ortahisar", ProvinceId = 61 },
                new City { Id = 826, Name = "Çemişgezek", ProvinceId = 62 },
                new City { Id = 827, Name = "Hozat", ProvinceId = 62 },
                new City { Id = 828, Name = "Mazgirt", ProvinceId = 62 },
                new City { Id = 829, Name = "Nazımiye", ProvinceId = 62 },
                new City { Id = 830, Name = "Ovacık / Tunceli", ProvinceId = 62 },
                new City { Id = 831, Name = "Pertek", ProvinceId = 62 },
                new City { Id = 832, Name = "Pülümür", ProvinceId = 62 },
                new City { Id = 833, Name = "Tunceli Merkez", ProvinceId = 62 },
                new City { Id = 834, Name = "Akçakale", ProvinceId = 63 },
                new City { Id = 835, Name = "Birecik", ProvinceId = 63 },
                new City { Id = 836, Name = "Bozova", ProvinceId = 63 },
                new City { Id = 837, Name = "Ceylanpınar", ProvinceId = 63 },
                new City { Id = 838, Name = "Halfeti", ProvinceId = 63 },
                new City { Id = 839, Name = "Hilvan", ProvinceId = 63 },
                new City { Id = 840, Name = "Siverek", ProvinceId = 63 },
                new City { Id = 841, Name = "Suruç", ProvinceId = 63 },
                new City { Id = 842, Name = "Viranşehir", ProvinceId = 63 },
                new City { Id = 843, Name = "Harran", ProvinceId = 63 },
                new City { Id = 844, Name = "Eyyübiye", ProvinceId = 63 },
                new City { Id = 845, Name = "Haliliye", ProvinceId = 63 },
                new City { Id = 846, Name = "Karaköprü", ProvinceId = 63 },
                new City { Id = 847, Name = "Banaz", ProvinceId = 64 },
                new City { Id = 848, Name = "Eşme", ProvinceId = 64 },
                new City { Id = 849, Name = "Karahallı", ProvinceId = 64 },
                new City { Id = 850, Name = "Sivaslı", ProvinceId = 64 },
                new City { Id = 851, Name = "Ulubey / Uşak", ProvinceId = 64 },
                new City { Id = 852, Name = "Uşak Merkez", ProvinceId = 64 },
                new City { Id = 853, Name = "Başkale", ProvinceId = 65 },
                new City { Id = 854, Name = "Çatak", ProvinceId = 65 },
                new City { Id = 855, Name = "Erciş", ProvinceId = 65 },
                new City { Id = 856, Name = "Gevaş", ProvinceId = 65 },
                new City { Id = 857, Name = "Gürpınar", ProvinceId = 65 },
                new City { Id = 858, Name = "Muradiye", ProvinceId = 65 },
                new City { Id = 859, Name = "Özalp", ProvinceId = 65 },
                new City { Id = 860, Name = "Bahçesaray", ProvinceId = 65 },
                new City { Id = 861, Name = "Çaldıran", ProvinceId = 65 },
                new City { Id = 862, Name = "Edremit / Van", ProvinceId = 65 },
                new City { Id = 863, Name = "Saray / Van", ProvinceId = 65 },
                new City { Id = 864, Name = "İpekyolu", ProvinceId = 65 },
                new City { Id = 865, Name = "Tuşba", ProvinceId = 65 },
                new City { Id = 866, Name = "Akdağmadeni", ProvinceId = 66 },
                new City { Id = 867, Name = "Boğazlıyan", ProvinceId = 66 },
                new City { Id = 868, Name = "Çayıralan", ProvinceId = 66 },
                new City { Id = 869, Name = "Çekerek", ProvinceId = 66 },
                new City { Id = 870, Name = "Sarıkaya", ProvinceId = 66 },
                new City { Id = 871, Name = "Sorgun", ProvinceId = 66 },
                new City { Id = 872, Name = "Şefaatli", ProvinceId = 66 },
                new City { Id = 873, Name = "Yerköy", ProvinceId = 66 },
                new City { Id = 874, Name = "Yozgat Merkez", ProvinceId = 66 },
                new City { Id = 875, Name = "Aydıncık / Yozgat", ProvinceId = 66 },
                new City { Id = 876, Name = "Çandır", ProvinceId = 66 },
                new City { Id = 877, Name = "Kadışehri", ProvinceId = 66 },
                new City { Id = 878, Name = "Saraykent", ProvinceId = 66 },
                new City { Id = 879, Name = "Yenifakılı", ProvinceId = 66 },
                new City { Id = 880, Name = "Çaycuma", ProvinceId = 67 },
                new City { Id = 881, Name = "Devrek", ProvinceId = 67 },
                new City { Id = 882, Name = "Ereğli / Zonguldak", ProvinceId = 67 },
                new City { Id = 883, Name = "Zonguldak Merkez", ProvinceId = 67 },
                new City { Id = 884, Name = "Alaplı", ProvinceId = 67 },
                new City { Id = 885, Name = "Gökçebey", ProvinceId = 67 },
                new City { Id = 886, Name = "Kilimli", ProvinceId = 67 },
                new City { Id = 887, Name = "Kozlu", ProvinceId = 67 },
                new City { Id = 888, Name = "Aksaray Merkez", ProvinceId = 68 },
                new City { Id = 889, Name = "Ortaköy / Aksaray", ProvinceId = 68 },
                new City { Id = 890, Name = "Ağaçören", ProvinceId = 68 },
                new City { Id = 891, Name = "Güzelyurt", ProvinceId = 68 },
                new City { Id = 892, Name = "Sarıyahşi", ProvinceId = 68 },
                new City { Id = 893, Name = "Eskil", ProvinceId = 68 },
                new City { Id = 894, Name = "Gülağaç", ProvinceId = 68 },
                new City { Id = 895, Name = "Bayburt Merkez", ProvinceId = 69 },
                new City { Id = 896, Name = "Aydıntepe", ProvinceId = 69 },
                new City { Id = 897, Name = "Demirözü", ProvinceId = 69 },
                new City { Id = 898, Name = "Ermenek", ProvinceId = 70 },
                new City { Id = 899, Name = "Karaman Merkez", ProvinceId = 70 },
                new City { Id = 900, Name = "Ayrancı", ProvinceId = 70 },
                new City { Id = 901, Name = "Kazımkarabekir", ProvinceId = 70 },
                new City { Id = 902, Name = "Başyayla", ProvinceId = 70 },
                new City { Id = 903, Name = "Sarıveliler", ProvinceId = 70 },
                new City { Id = 904, Name = "Delice", ProvinceId = 71 },
                new City { Id = 905, Name = "Keskin", ProvinceId = 71 },
                new City { Id = 906, Name = "Kırıkkale Merkez", ProvinceId = 71 },
                new City { Id = 907, Name = "Sulakyurt", ProvinceId = 71 },
                new City { Id = 908, Name = "Bahşili", ProvinceId = 71 },
                new City { Id = 909, Name = "Balışeyh", ProvinceId = 71 },
                new City { Id = 910, Name = "Çelebi", ProvinceId = 71 },
                new City { Id = 911, Name = "Karakeçili", ProvinceId = 71 },
                new City { Id = 912, Name = "Yahşihan", ProvinceId = 71 },
                new City { Id = 913, Name = "Batman Merkez", ProvinceId = 72 },
                new City { Id = 914, Name = "Beşiri", ProvinceId = 72 },
                new City { Id = 915, Name = "Gercüş", ProvinceId = 72 },
                new City { Id = 916, Name = "Kozluk", ProvinceId = 72 },
                new City { Id = 917, Name = "Sason", ProvinceId = 72 },
                new City { Id = 918, Name = "Hasankeyf", ProvinceId = 72 },
                new City { Id = 919, Name = "Beytüşşebap", ProvinceId = 73 },
                new City { Id = 920, Name = "Cizre", ProvinceId = 73 },
                new City { Id = 921, Name = "İdil", ProvinceId = 73 },
                new City { Id = 922, Name = "Silopi", ProvinceId = 73 },
                new City { Id = 923, Name = "Şırnak Merkez", ProvinceId = 73 },
                new City { Id = 924, Name = "Uludere", ProvinceId = 73 },
                new City { Id = 925, Name = "Güçlükonak", ProvinceId = 73 },
                new City { Id = 926, Name = "Bartın Merkez", ProvinceId = 74 },
                new City { Id = 927, Name = "Kurucaşile", ProvinceId = 74 },
                new City { Id = 928, Name = "Ulus", ProvinceId = 74 },
                new City { Id = 929, Name = "Amasra", ProvinceId = 74 },
                new City { Id = 930, Name = "Ardahan Merkez", ProvinceId = 75 },
                new City { Id = 931, Name = "Çıldır", ProvinceId = 75 },
                new City { Id = 932, Name = "Göle", ProvinceId = 75 },
                new City { Id = 933, Name = "Hanak", ProvinceId = 75 },
                new City { Id = 934, Name = "Posof", ProvinceId = 75 },
                new City { Id = 935, Name = "Damal", ProvinceId = 75 },
                new City { Id = 936, Name = "Aralık", ProvinceId = 76 },
                new City { Id = 937, Name = "Iğdır Merkez", ProvinceId = 76 },
                new City { Id = 938, Name = "Tuzluca", ProvinceId = 76 },
                new City { Id = 939, Name = "Karakoyunlu", ProvinceId = 76 },
                new City { Id = 940, Name = "Yalova Merkez", ProvinceId = 77 },
                new City { Id = 941, Name = "Altınova", ProvinceId = 77 },
                new City { Id = 942, Name = "Armutlu", ProvinceId = 77 },
                new City { Id = 943, Name = "Çınarcık", ProvinceId = 77 },
                new City { Id = 944, Name = "Çiftlikköy", ProvinceId = 77 },
                new City { Id = 945, Name = "Termal", ProvinceId = 77 },
                new City { Id = 946, Name = "Eflani", ProvinceId = 78 },
                new City { Id = 947, Name = "Eskipazar", ProvinceId = 78 },
                new City { Id = 948, Name = "Karabük Merkez", ProvinceId = 78 },
                new City { Id = 949, Name = "Ovacık / Karabük", ProvinceId = 78 },
                new City { Id = 950, Name = "Safranbolu", ProvinceId = 78 },
                new City { Id = 951, Name = "Yenice / Karabük", ProvinceId = 78 },
                new City { Id = 952, Name = "Kilis Merkez", ProvinceId = 79 },
                new City { Id = 953, Name = "Elbeyli", ProvinceId = 79 },
                new City { Id = 954, Name = "Musabeyli", ProvinceId = 79 },
                new City { Id = 955, Name = "Polateli", ProvinceId = 79 },
                new City { Id = 956, Name = "Bahçe", ProvinceId = 80 },
                new City { Id = 957, Name = "Kadirli", ProvinceId = 80 },
                new City { Id = 958, Name = "Osmaniye Merkez", ProvinceId = 80 },
                new City { Id = 959, Name = "Düziçi", ProvinceId = 80 },
                new City { Id = 960, Name = "Hasanbeyli", ProvinceId = 80 },
                new City { Id = 961, Name = "Sumbas", ProvinceId = 80 },
                new City { Id = 962, Name = "Toprakkale", ProvinceId = 80 },
                new City { Id = 963, Name = "Akçakoca", ProvinceId = 81 },
                new City { Id = 964, Name = "Düzce Merkez", ProvinceId = 81 },
                new City { Id = 965, Name = "Yığılca", ProvinceId = 81 },
                new City { Id = 966, Name = "Cumayeri", ProvinceId = 81 },
                new City { Id = 967, Name = "Gölyaka", ProvinceId = 81 },
                new City { Id = 968, Name = "Çilimli", ProvinceId = 81 },
                new City { Id = 969, Name = "Gümüşova", ProvinceId = 81 },
                new City { Id = 970, Name = "Kaynaşlı", ProvinceId = 81 }
                );

        }
    }
}
